### ISSUE TITLE
Trap representations

### ISSUE THREAD

**Issue by mversic** [loyd/fixnum#32]
Hi,

am I safe to assume that there are no trap representations of `FixedPoint<I, U>`? To paraphrase, can `FixedPoint` always be safely transmuted to and from `I`? I have the feeling this is so, but I'd like a confirmation

**Comment by loyd** [comment]
Yep. It seems that `repr(transparent)` is enough as a guarantee.

**Comment by mversic** [comment]
Well, the reason I'm asking this question is because `repr(transparent)` isn't always enough. For instance, you cannot always transmute `*mut T` into `NoNull<T>`, you need to make sure the pointer isn't `null` before doing the transmute. Not all bit patterns are valid for the newtype wrapper

**Comment by loyd** [comment]
How does the representation of `FixedPoint` relate to `*mut FixedPoint`? Are you trying to cast `FixedPoint` to `*mut FixedPoint`?

The original question is
> To paraphrase, can FixedPoint always be safely transmuted to and from I

And here `transparent` should be enough.

**Comment by mversic** [comment]
> How does the representation of `FixedPoint` relate to `*mut FixedPoint`? Are you trying to cast `FixedPoint` to `*mut FixedPoint`?

Haha, ofc not. I was just concerned whether there was a value in the underlying integer that is not allowed by the as a `FixNum` value

> And here `transparent` should be enough. 

Ok then

**Comment by loyd** [comment]
> I was just concerned whether there was a value in the underlying integer that is not allowed by the as a FixNum value

Ok. No, all values are acceptable.
